### PR TITLE
Using Datasources added

### PR DESCRIPTION
**Pull request by Kobigan1223**
Using Datasources added

### CODE REVIEW

**Comment by Kobigan1223** [comment]
Using Datasources added

**Comment by sithumonline** [comment]
> Using Datasources added

Hi @Kobigan1223 add all the changes you want then do the PR otherwise I have to approve one by one

**Comment by Kobigan1223** [comment]
Okk @sithumonline

**Comment by Kobigan1223** [comment]
Datasources Fully Updated

**Comment by Kobigan1223** [comment]
@sithumonline  Now Fully updated

**Review by sithumonline — APPROVED** [review]

**Pull request merged**
