### PR TITLE
Added docker-compose doc closes #22

### LINKED ISSUE #22: Write a doc about docker-compose
**_Please assign yourself before you start work on it._**

### PR DESCRIPTION
**Pull request by RahulPalve**

### CODE REVIEW

**Comment by RahulPalve** [comment]
Please add `hacktoberfest` and `hacktoberfest-accepted` lables

**Comment by sithumonline** [comment]
Please add `_category_.json` file like  https://github.com/sliit-foss/zero2hero/blob/master/docs/machine-learning/_category_.json

And link example yaml file to md file otherwise readers can't find it.

**Comment by sithumonline** [comment]
You missed `sidebar_position`
Add it like

**Comment by RahulPalve** [comment]
Done

**Review by sithumonline — APPROVED** [review]
Nice, your so fast I love it 💜

**Pull request merged**
